### PR TITLE
changed var keywords to let keywords

### PR DESCRIPTION
**Pull request by MilesZew**
let is better than var for a few reasons

### CODE REVIEW

**Comment by willstocks-tech** [comment]
Hi @MilesZew

Thanks for getting involved and popping this PR in! 

Apologies, I don't have a PR template yet, but would you be willing to expand on your comment for me:

> let is better than var for a few reasons

Performance reasons? Cleanliness reasons? Memory reasons?

Also, I'm about to deprecate the `-consolemessages` version of the script in #11 so if you'd be willing to amend your PR to make the changes to [dynamicpolyfill.js](https://github.com/willstocks-tech/dynamically-polyfill-features-for-a-script/blob/develop/dynamicpolyfill.js) instead, that'd be AMAZING! 😄

**Comment by willstocks-tech** [comment]
Just to confirm - `dynamicpolyfill-consolemessages.js` has now been deprecated with the [v0.0.5 release](https://github.com/willstocks-tech/dynamically-polyfill-features-for-a-script/releases/tag/0.0.5)! 

This file now no longer exists.

CC: @MilesZew - as the PR you have proposed is now unmergeable due to the missing file.

**Comment by MilesZew** [comment]
Thank You for letting me know, I will be more clear in my next pull request. I am currently working on a promise polyfill incase you were planning on working on it.

**Comment by willstocks-tech** [comment]
Ahhhh, nice one @MilesZew!! I will keep an eye out! 😄  I keep intending to pick up issue #1 but keep getting distracted! At the moment, I'm just finishing ironing out PR #19 before moving on to any of the other issues.

I created a PR template which hopefully covers the basics (some bits can probably be ignored in some cases). If you PR in again, I'm happy to list you as a "contributor" 😁

**Pull request closed without merging**
